package ch.ethz.coss.nervousnet.vm.storage;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TRAFFIC_DATA.
 */
public class TrafficData implements SensorDataImpl {

    private Long id;
    private Long TimeStamp;
    private String appName;
    private Long txBytes;
    private Long rxBytes;
    private Boolean ShareFlag;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TrafficData() {
    }

    public TrafficData(Long id) {
        this.id = id;
    }

    public TrafficData(Long id, Long TimeStamp, String appName, Long txBytes, Long rxBytes, Boolean ShareFlag) {
        this.id = id;
        this.TimeStamp = TimeStamp;
        this.appName = appName;
        this.txBytes = txBytes;
        this.rxBytes = rxBytes;
        this.ShareFlag = ShareFlag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Long getTxBytes() {
        return txBytes;
    }

    public void setTxBytes(Long txBytes) {
        this.txBytes = txBytes;
    }

    public Long getRxBytes() {
        return rxBytes;
    }

    public void setRxBytes(Long rxBytes) {
        this.rxBytes = rxBytes;
    }

    public Boolean getShareFlag() {
        return ShareFlag;
    }

    public void setShareFlag(Boolean ShareFlag) {
        this.ShareFlag = ShareFlag;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
